[package]
name = "behavioral_drift_detection"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
tokio = { version = "1.37", features = ["full"] }
once_cell = "1.19"
tracing = "0.1"
tracing-subscriber = "0.3"
rand = "0.9.1"
