[package]
name    = "retry_backoff"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
backoff = "0.4"
tokio   = { version = "1", features = ["rt", "macros", "time"] }
anyhow  = "1"
