[package]
name = "micro_services_mesh"
version = "0.1.0"
edition = "2024"

[dependencies]
kube   = { version = "0.92", features = ["runtime"] }
serde  = { version = "1", features = ["derive"] }
anyhow = "1"
tokio  = { version = "1", features = ["rt", "macros"] }

