[package]
name = "strangler_refactor"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
anyhow   = "1"
tokio    = { version = "1", features = ["rt", "macros"] }

