[package]
name    = "circuit_breaker"
version = "0.1.0"
edition = "2021"

[dependencies]
tower         = { version = "0.4", features = ["util"] }
futures-util  = "0.3"
anyhow        = "1"
tokio         = { version = "1", features = ["rt", "macros", "time"] }
